/*!
 * *****************************************************************************
 *  mmm-jast
 *  Version 2.10.3
 *
 *  A minimalistic stock ticker based on Yahoo's finance API for the MagicMirror² platform.
 *  Please submit bugs at: https://github.com/jalibu/MMM-Jast/issues
 *
 *  (c) Jan Litzenburger (Jan.Litzenburger@gmail.com)
 *  Licence: MIT
 *
 *  This file is auto-generated. Do not edit this file directly.
 * *****************************************************************************
 */

(function (Log) {
  "use strict";

  /**
   * Safely wraps module exports in an isolated object to avoid polluting the global scope.
   * Ensures that only the necessary properties are exposed.
   */
  function wrapExports(module) {
    const wrapped = Object.create(null);
    if (module) {
      Object.keys(module).forEach((key) => {
        if (key !== "default") {
          const descriptor = Object.getOwnPropertyDescriptor(module, key);
          Object.defineProperty(wrapped, key, descriptor.get
            ? descriptor
            : { enumerable: true, get: () => module[key] });
        }
      });
    }
    wrapped.default = module;
    return Object.freeze(wrapped);
  }

  const exports = wrapExports(Log);

  /**
   * A set of utility methods used throughout MMM-Jast.
   * Handles number formatting, stock calculations, and portfolio aggregation.
   */
  const utils = {
    /**
     * Returns number formatting options for stock values.
     */
    getCurrentValueStyle: (config) => ({
      style: config.showCurrency ? "currency" : "decimal",
      useGrouping: config.useGrouping,
      currencyDisplay: config.currencyStyle,
      minimumFractionDigits: Math.min(config.numberDecimalsValues, 8),
      maximumFractionDigits: Math.min(config.numberDecimalsValues, 8)
    }),

    /**
     * Returns number formatting options for stock change (absolute) values.
     */
    getChangeValueStyle: (config) => ({
      style: config.showChangeValueCurrency ? "currency" : "decimal",
      useGrouping: config.useGrouping,
      currencyDisplay: config.currencyStyle,
      minimumFractionDigits: Math.min(config.numberDecimalsValues, 8),
      maximumFractionDigits: Math.min(config.numberDecimalsValues, 8)
    }),

    /**
     * Returns formatting options for percentages.
     */
    getPercentStyle: (config) => ({
      style: "percent",
      useGrouping: config.useGrouping,
      minimumFractionDigits: Math.min(config.numberDecimalsPercentages, 8)
    }),

    /**
     * Determines how many stocks should be shown based on visibility settings.
     */
    getNumberOfDisplayedStocks: (stocks, config) =>
      config.showHiddenStocks
        ? stocks.length
        : stocks.filter((s) => !s.meta.hidden).length,

    /**
     * Gets the absolute market change for a given stock.
     */
    getStockChange: (stock) => stock.price?.regularMarketChange ?? 0,

    /**
     * Gets the percentage market change for a given stock.
     */
    getStockChangePercent: (stock) => stock.price?.regularMarketChangePercent ?? 0,

    /**
     * Gets the current regular market price for a stock.
     */
    getCurrentValue: (stock) => stock.price?.regularMarketPrice ?? 0,

    /**
     * Calculates performance (gain/loss) based on purchase price.
     */
    getStockPerformance: (stock) =>
      stock.meta.purchasePrice
        ? utils.getCurrentValue(stock) - stock.meta.purchasePrice
        : 0,

    /**
     * Formats the performance (gain/loss) as a currency string.
     */
    getStockPerformanceAsString: (stock, config) =>
      utils.getStockPerformance(stock).toLocaleString(
        config.locale,
        Object.assign(utils.getChangeValueStyle(config), {
          currency: stock.price?.currency ?? "USD"
        })
      ),

    /**
     * Formats the total performance value (e.g., gain/loss multiplied by quantity).
     */
    getStockPerformanceSumAsString: (stock, config) =>
      (utils.getStockPerformance(stock) * (stock.meta.quantity ?? 0)).toLocaleString(
        config.locale,
        Object.assign(utils.getChangeValueStyle(config), {
          currency: stock.price?.currency ?? "USD"
        })
      ),

    /**
     * Formats performance as a percentage (compared to purchase price).
     */
    getStockPerformancePercentAsString: (stock, config) =>
      (
        stock.meta.purchasePrice
          ? (utils.getCurrentValue(stock) - stock.meta.purchasePrice) /
            stock.meta.purchasePrice
          : 0
      ).toLocaleString(config.locale, utils.getPercentStyle(config)),

    /**
     * Formats current stock value as a string.
     */
    getCurrentValueAsString: (stock, config) =>
      utils.getCurrentValue(stock).toLocaleString(
        config.locale,
        Object.assign(utils.getCurrentValueStyle(config), {
          currency: stock.price?.currency ?? "USD"
        })
      ),

    /**
     * Formats the purchase price (if available).
     */
    getPurchasePriceAsString: (stock, config) =>
      (stock.meta.purchasePrice ?? 0).toLocaleString(
        config.locale,
        Object.assign(utils.getCurrentValueStyle(config), {
          currency: stock.price?.currency ?? "USD"
        })
      ),

    /**
     * Returns the preferred human-readable stock name.
     */
    getStockName: (stock) => stock.meta.name || stock.price?.longName || "",

    /**
     * Formats timestamp values such as “last updated” into a readable string.
     * Supports placeholders like HH:mm:ss, DD.MM.YYYY, etc.
     */
    formatDate: (timestamp, format) => {
      const date = new Date(timestamp);
      const pad = (num) => String(num).padStart(2, "0");

      return format
        .replace("HH", pad(date.getHours()))
        .replace("mm", pad(date.getMinutes()))
        .replace("ss", pad(date.getSeconds()))
        .replace("DD", pad(date.getDate()))
        .replace("MM", pad(date.getMonth() + 1))
        .replace("YYYY", String(date.getFullYear()));
    },

    /**
     * Aggregates values across all user-held stocks to produce a portfolio summary.
     * Computes total value, old value, and purchase value for comparison.
     */
    getPortfolio(stocks, config) {
      const portfolio = [];
      for (const stock of stocks) {
        try {
          const userConfig = config.stocks?.find(
            (s) => s.symbol === stock.meta?.symbol
          );

          // Skip if no quantity or missing price data
          if (userConfig?.quantity && stock.price) {
            const price = stock.price.regularMarketPrice ?? 0;
            const change = stock.price.regularMarketChange ?? 0;
            const quantity = userConfig.quantity;

            const currentValue = price * quantity;
            const oldValue = (price - change) * quantity;
            const currency = stock.price?.currency ?? "";

            // Use configured purchase price or fallback to current price
            const purchaseValue = (userConfig.purchasePrice ?? price) * quantity;

            // If the same currency already exists, merge values
            const existing = portfolio.find((p) => p.currency === currency);
            if (existing) {
              existing.value += currentValue;
              existing.oldValue += oldValue;
              existing.purchaseValue += purchaseValue;
            } else {
              portfolio.push({
                value: currentValue,
                purchaseValue,
                oldValue,
                currency
              });
            }
          }
        } catch (err) {
          Log.warn("There was a problem calculating portfolio growth:", err);
        }
      }
      return portfolio;
    }
  };

  /**
   * The main MagicMirror² module definition for MMM-Jast.
   * Handles configuration defaults, template rendering, and live stock updates.
   */
  Module.register("MMM-Jast", {
    /**
     * Default configuration for the module.
     */
    defaults: {
      currencyStyle: "code",
      fadeSpeedInSeconds: 3.5,
      lastUpdateFormat: "HH:mm",
      locale: config.locale || "en-GB",
      maxChangeAge: 86400000, // 24 hours
      maxWidth: "100%",
      numberDecimalsPercentages: 1,
      numberDecimalsValues: 2,
      displayMode: "vertical",
      showColors: true,
      showCurrency: true,
      showChangePercent: true,
      showChangeValue: false,
      showChangeValueCurrency: false,
      showHiddenStocks: false,
      showLastUpdate: false,
      showPortfolioGrowth: false,
      showPortfolioGrowthPercent: false,
      showPortfolioValue: false,
      showPortfolioPerformanceValue: false,
      showPortfolioPerformancePercent: false,
      showStockPerformanceValue: false,
      showStockPerformanceValueSum: false,
      showStockPerformancePercent: false,
      updateIntervalInSeconds: 600,
      useGrouping: false,
      virtualHorizontalMultiplier: 2,
      stocksPerPage: 2,
      stocks: [
        { name: "BASF", symbol: "BAS.DE", quantity: 10, purchasePrice: 70.4 },
        { name: "SAP", symbol: "SAP.DE", quantity: 15, purchasePrice: 90.3 },
        { name: "Henkel", symbol: "HEN3.DE", hidden: true },
        { name: "Bitcoin", symbol: "BTC-EUR" }
      ]
    },

    /**
     * Loads required CSS files.
     */
    getStyles() {
      return ["MMM-Jast.css"];
    },

    /**
     * Defines available translations for supported languages.
     */
    getTranslations() {
      return {
        en: "translations/en.json",
        de: "translations/de.json"
      };
    },

    /**
     * Specifies the Nunjucks template used for rendering.
     */
    getTemplate() {
      return "templates/MMM-Jast.njk";
    },

    /**
     * Provides data and configuration to the rendering template.
     */
    getTemplateData() {
      return {
        config: this.config,
        stocks: this.state?.stocks,
        lastUpdate: utils.formatDate(
          this.state?.lastUpdate ?? Date.now(),
          this.config.lastUpdateFormat
        ),
        utils
      };
    },

    /**
     * Called when the module is loaded. Starts data retrieval and timers.
     */
    start() {
      // Automatically migrate deprecated config property
      if (this.config.scroll) {
        Log.warn("MMM-JAST config property 'scroll' is deprecated. Use 'displayMode' instead.");
        this.config.displayMode = this.config.scroll;
      }

      this.loadData();
      this.scheduleUpdate();
      this.updateDom();
    },

    /**
     * Schedules periodic data refreshes based on configured interval.
     */
    scheduleUpdate() {
      this.config.updateIntervalInSeconds = Math.max(this.config.updateIntervalInSeconds, 120);
      setInterval(() => {
        this.loadData();
      }, 1000 * this.config.updateIntervalInSeconds);
    },

    /**
     * Requests updated stock data from the backend via socket notification.
     */
    loadData() {
      this.sendSocketNotification(`JAST_STOCKS_REQUEST-${this.identifier}`, this.config);
    },

    /**
     * Receives updated stock data and triggers a DOM update.
     */
    socketNotificationReceived(notification, payload) {
      if (notification === `JAST_STOCKS_RESPONSE-${this.identifier}`) {
        this.state = payload;
        this.updateDom();
        Log.debug("Stock data received:", payload);
      }
    }
  });

})(Log);

